#!/bin/bash
main() {

  set -o errexit
  set -o pipefail
  set -o nounset

  local -r dirname="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  source "${dirname}"/../env.sh

  # Copy configuration files and ssh keys to the docker context folder.
  cp "${GIT_CONFIG}" "${DOCKER_CONTEXT}"
  cp "${SSH_FOLDER}"/"${SSH_PRIVATE_KEY_FILE}" "${DOCKER_CONTEXT}"
  cp "${SSH_FOLDER}"/"${SSH_PUBLIC_KEY_FILE}" "${DOCKER_CONTEXT}"
  cp "${SSH_FOLDER}"/"${SSH_CONFIG_FILE}" "${DOCKER_CONTEXT}"
  cp "${BASH_RC}" "${DOCKER_CONTEXT}"

  # Build dockerfile.
  docker build --tag="${IMAGE}":"${VERSION}" --rm -f "${DOCKERFILE_DEVEL}" "${DOCKER_CONTEXT}" \
               --build-arg DUT_SERVER_IP="${DUT_IP}" \
               --build-arg TREX_SERVER_IP="${TREX_SERVER_IP}" \
               --build-arg JUMP_SERVER_USERNAME="${JUMP_SERVER_USERNAME}" \
               --build-arg JUMP_SERVER_IP="${JUMP_SERVER_IP}" \
               --build-arg JUMP_SERVER_PORT="${JUMP_SERVER_PORT}"

  # Remove configuration files and ssh keys from the docker context folder.
  rm "${DOCKER_CONTEXT}"/.gitconfig
  rm "${DOCKER_CONTEXT}"/"${SSH_PRIVATE_KEY_FILE}"
  rm "${DOCKER_CONTEXT}"/"${SSH_PUBLIC_KEY_FILE}"
  rm "${DOCKER_CONTEXT}"/"${SSH_CONFIG_FILE}"
  rm "${DOCKER_CONTEXT}"/.bashrc
}

main "$@"
