#!/usr/bin/env bash
main() {

  set -o errexit
  set -o pipefail
  set -o nounset

  local -r dirname="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  source "${dirname}"/../env.sh

	docker run -it --rm \
		--env-file "${dirname}"/../env.sh \
		--volume "${dirname}"/../:"${WORKSPACE}" \
		--privileged \
		--workdir "${WORKSPACE}" "${IMAGE_TAG}":"${IMAGE_VERSION}" \
		/bin/bash

  exit 0
}
main "$@"
