#!/usr/bin/env bash
#
# Copy package with binary and libraries.

main() {

  set -o errexit
  set -o pipefail
  set -o nounset

  local -r dirname="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  local -r filename="${dirname}/$(basename "${BASH_SOURCE[0]}")"

  source "${dirname}"/../../env.sh

  echo
  echo "Copy package with binary and libraries."
  echo
  scp -r "${LOCAL_PACKAGE}" "${TREX_CLIENT_SSH}":"${DUT_UPLOAD_DIR}"
  exit 0
}

main "$@"
