#!/usr/bin/env bash
#
# Install t-rex.

main() {

  set -o errexit
  set -o pipefail
  set -o nounset

  local -r dirname="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  local -r upload_dir="${1:-/tmp/}"
  local -r trex_version="${2:-v2.38}"
  local -r trex_shasum="${3:-290c1be468335a2de2e69f217b139c9b1198732e529bfd069348d05297548b8a}"
  local -r shasum=$(cat "${upload_dir}"/"${trex_version}".tar.gz | sha256sum | awk '{print $1}')

  echo
  echo "Installation folder: "${upload_dir}""
  echo "Installation version: "${trex_version}""
  echo "Installation sha256sum: "${trex_shasum}""
  echo

  mkdir -p "${upload_dir}"
  if [ ! -f "${upload_dir}"/"${trex_version}".tar.gz ] \
        || [ "${trex_shasum}" != "${shasum}" ] \
        && [ ! -d "${upload_dir}"/"${trex_version}" ]; then
    rm -f "${upload_dir}"/"${trex_version}".tar.gz
    cd "${upload_dir}"
    wget --no-cache --no-check-certificate https://trex-tgn.cisco.com/trex/release/"${trex_version}".tar.gz
    tar -xzvf "${trex_version}".tar.gz
    rm "${trex_version}".tar.gz
  fi

  echo "The t-rex installation was successful!"

  exit 0
}

main "$@"
