#!/usr/bin/env bash
#
# Install the t-rex on server.

main() {

  set -o errexit
  set -o pipefail
  set -o nounset
  set -x

  local -r dirname="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  source "${dirname}"/environment.sh

  # Execute local script (install_trex) on the server.

  echo
  echo "Installing t-rex on "${TREX_SERVER_IP}""
  echo
  ssh "${TREX_SERVER_SSH}" "bash -s" -- "${TREX_SERVER_UPLOAD_DIR}" "${TREX_VERSION}" <"${dirname}"/install_trex
}

main "$@"
