#!/usr/bin/env bash
#
# Install the t-rex on server.

main() {

  set -o errexit
  set -o pipefail
  set -o nounset
  set -x

  local -r dirname="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  source "${dirname}"/environment.sh

  # Execute local script (install_trex) on the server.

  echo
  echo "Installing t-rex on "${TREX_SERVER_IP}""
  echo
  if [ -n "${TREX_SERVER_NAME}" ]; then
    ssh "${TREX_SERVER_NAME}" "bash -s" -- < "${dirname}"/install_trex  "${TREX_SERVER_UPLOAD_DIR}" "${TREX_VERSION}"
  else
    ssh "${TREX_SERVER_USERNAME}"@"${TREX_SERVER_IP}" "bash -s" -- < "${dirname}"/install_trex  "${TREX_SERVER_UPLOAD_DIR}" "${TREX_VERSION}"
  fi
}

main "$@"
